flox/floxdocs

- docs/cookbook/languages/rust.md
- mkdocs.yml
This also disables the `toc.integrate` option, which moves the page table of contents to the right side of the page instead of nesting it under the navigation menu.
> feat: add Rust cookbook page

- docs/cookbook/languages/rust.md
This is necessary on macOS and was just left out by mistake
> chore: add libiconv for rust cookbook

- docs/tutorials/sharing-environments.md
Adds `flox pull --copy` to sharing guide
> feat: flox pull --copy in sharing guide

- docs/concepts/manifest-builds.md
- docs/cookbook/builds/examples.md
ℹ️ This merges into `build-preview` which will be published at https://build-preview--floxdocs.netlify.app/
Add a sub-section about the other `sandbox=pure` mode that we currently
support, including the caveat that networking access is only sandboxed
on Linux.
I've created a couple of new bugs/ehancements in the process:
- https://github.com/flox/flox/issues/2461
- https://github.com/flox/flox/issues/2462
Plus a few typos and tweaks that are in separate commits.
> feat(build): Document sandboxed builds

- .github/actions/common-setup/action.yml
Currently, when selecting a remote builder to run tests on, or build against, we always select the one at top of the list. This isn't really taking full advantage of our infrastructure, since we offer multiple machines for all architectures currently.
This introduces a `shuf` before we select the builder.
Refs: flox/deltaops#375
> Shuffle remote builders

- docs/tutorials/sharing-environments.md
⚠️ Don't merge before https://github.com/flox/flox/pull/2478 is released.
---
Now that we've:
1. Made it easier to use with `--tag` and `--runtime` support.
2. Added support for macOS.
Plus some other tidy ups while we're here.
- Old: https://flox.dev/docs/tutorials/sharing-environments/#sharing-with-containers
- New: https://5f6e9be35dee26908e207d99237f146d18f35992--floxdocs.netlify.app/docs/tutorials/sharing-environments/#sharing-with-containers
> doc(sharing): Remove containerize warning

- docs/tutorials/default-environment.md
Update docs to match https://github.com/flox/flox/pull/2505/
/usr/local/bin is not in path until path_helper runs which is run via /etc/profile, so flox won't be found.
We could recommend using the absolute path to flox, but path_helper will then put other paths in front of paths for the default environment.
Make the same recommendation on Linux for consistency. The default environment won't be activated for non-login non-interactive shells, but that behavior seems acceptable.
> fix: recommend .zshrc and .zprofile for default env

- docs/tutorials/migrations/nvm.md
- I am going to hold off on adding the "node hopping" section for now, because as Ross pointed out, it's not quite as seamless to run `flox activate -d ~/node-versions/20` as it is to run `nvm use 20`, given the added overhead of creating the Flox environment manually for each node version that you might want to use. My view is that the guide handles the most common use cases, but do correct me if you disagree!
- I have tried to simplify the process of describing an upgrade, where I encourage the user to edit the manifest rather than using `uninstall` and then `install`.
- I added some information about installing other project dependencies using Flox, so hopefully it's now clear that Flox does a lot more than just manage Node.js versions
> feat: Add nvm migration guide

- check_links.sh
- docs/tutorials/migrations/nvm.md
- Added a section on `node-gyp`, because this is definitely an area where Flox will shine in comparison with nvm (thanks, @stahnma)
- Added an optional section about using a `pkg-group`, which I'm recommending in cases where the Node.js version to install is on the older side
- Added some clarification about the `nodejs` package versus those that have numerical suffixes
> docs(nvm.md): Update nvm migration guide per feedback

- docs/tutorials/migrations/nvm.md
I solicited feedback from a former colleague, who made the very helpful suggestion that each command that the user is meant to run should be rendered in its own snippet that can be copied by clicking on the copy to clipboard button. This makes the guide more user friendly and prevents any issues that might arise when the reader misses a command that's embedded in a block of text.
> docs(nvm.md): Improve utility of Flox command snippets

- docs/concepts/manifest-builds.md
I got confused and used the attr_path in `runtime-packages` at first.  Thought it would be good to make this explicit and update the example to reflect the difference.  I question using the `hello-go` package, but wanted a different install-id from the pkg-path.
> fix: clarify the runtime-packages build option

- .flox/env/manifest.lock
- .flox/env/manifest.toml
- .github/workflows/ci.yml
- .markdownlint-cli2.yaml
- docs/tutorials/migrations/homebrew.md
- docs/tutorials/migrations/nvm.md
Fixes some issues that were described in this thread:
- https://flox-dev.slack.com/archives/C055P1JCP5L/p1736368190737079
**flox: Upgrade markdownlint and lychee**
I want `gitignore` support from `markdownlint-cli2` but it wasn't
available in the version that was pinned by `python.version` in the
`toplevel` package group.
I've moved `lychee` to a new group at the same time because it felt
weird having a group for a single package and I can safely verify that
these don't introduce any breaking changes.
**ci: Move markdownlint globs to config**
This fixes a bug whereby the globs were being incorrectly expanded by
the shell before being passed to `markdownlint-cli2` because they
weren't quoted as the docs suggest.
Depending on the shell in use this could cause it to:
- incorrectly miss …
> Fix linting

- check_links.sh
- docs/concepts/manifest-builds.md
- docs/concepts/packages-and-catalog.md
- docs/concepts/publishing.md
- mkdocs.yml
This change reworks the existing build concept page and adds a publishing concept page. In the future there will be links to other pages that are currently in progress.
> feat: add build and publish concept pages

- docs/install-flox.md
Research participant noted that the install button doesn't list M3, and wondered if we support it. We do!
> Add M3 to mac install button text

- docs/cookbook/publish/signing-keys.md
After adding a new trusted key you need to restart the Nix daemon, and this was not previously mentioned in the docs.
> fix: restart the nix daemon

- docs/tutorials/default-environment.md
New shells inherit the CWD they are started in
and may thus activate a differnt env than the "default" environment. Rather than relying on smart defaulting, recommend adding a `-d ~` arg in rcfiles.
Originally reported: https://discourse.flox.dev/t/default-environment-activation-in-docs-tutorial-should-look-different-imo/1114
> Consistently recommend adding `-d ~` to activations from rcfiles

- docs/tutorials/multi-arch-environments.md
The CLI now automatically restricts systems when installing a package
that doesn't support all 4 systems. Update the multi-arch tutorial
accordingly.
> Reflect CLI changes in multi-arch tutorial

- .flox/env/manifest.lock
- .flox/env/manifest.toml
- docs/tutorials/customizing-environments.md
- mkdocs.yml
This previously focused exclusively on shell hooks and used them to run a service. This now shows a user how to leverage the hook, profile, and vars sections to customize their shell environment in an activated environment.
> feat: rewrite customizing environments

- docs/install-flox.md
There has been some confusion over Flox not being able to run as non-root in containers, see https://github.com/flox/flox/issues/1188
> Document container installs are root only

- docs/concepts/manifest-builds.md
The second commit contains the actual content changes.
Closes #237
> feat: update build concept page

- docs/concepts/organizations.md
This explains the RBAC model for orgs, and replaces the bits about
contacting us to make changes with an explanation of how to manage the
org in FloxHub.
> chore: Update orgs doc to explain how orgs are now managed

- docs/flox-5-minutes.md
- docs/index.md
- docs/install-flox/install.md
- docs/install-flox/uninstall.md
- docs/tutorials/migrations/homebrew.md
- docs/tutorials/migrations/nvm.md
- mkdocs.yml
Move the uninstall instructions to a separate page, and move upgrade instructions to the bottom of the install instructions per tab. 
Update all links throughout docs.
Reorder the tabs.
Remove the link to release notes.
> refactor: separate install and uninstall pages

- docs/concepts/nix-expression-builds.md
**docs(nef): Rename old -> oldAttrs**
To make it clearer that these are attrs.
The docs refer to these as `previousAttrs` but there's very little usage
of that in the single argument form in `nixos/nixpkgs`, where there's
mostly a 50:50 split between `old` and `oldAttrs`:
- https://nixos.org/manual/nixpkgs/stable/#sec-pkg-overrideAttrs
- https://github.com/search?q=repo%3ANixOS%2Fnixpkgs+overrideAttrs+old&type=code
- https://github.com/search?q=repo%3ANixOS%2Fnixpkgs+overrideAttrs+previousattrs&type=code
**docs(nef): Indicate unused oldAttrs**
We only need access to `finalAttrs` from the two argument form of
`overrideAttrs` so underscore the `oldAttrs` to make it clear that it's
not in use whilst still indicating it's name.
From https://nixos.org/manual/nixpkgs/stable/#sec-pkg-overrideAttr …
> docs(nef): Tweak overrideAttrs naming

- docs/tutorials/sharing-environments.md
Sebastian Schuberth noted in Slack that it wasn't clear `activate` would download packages that were previously `flox install`ed into an env:
- https://floxcommunitygroup.slack.com/archives/C06NYALM8P8/p1753282180636659
Clarify this by noting that it's the same environment and packages.
> docs(sharing): Clarify what activate does

- .markdownlint-cli2.yaml
- docs/cookbook/languages/go.md
I found a broken link while working on NEF docs and found that we can check these in CI:
- https://github.com/DavidAnson/markdownlint/blob/main/doc/md052.md
Output before the fix:
% markdownlint-cli2
markdownlint-cli2 v0.18.1 (markdownlint v0.38.0)
Finding: docs/**/*.md
Linting: 39 file(s)
Summary: 1 error(s)
docs/cookbook/languages/go.md:71:21 MD052/reference-links-images Reference links and images should use a label that is defined [Missing link or image reference definition: "pure-builds-section"] [Context: "[pure builds][pure-builds-section]"]
> fix: Lint and fix broken reference links

- docs/cookbook/languages/c.md
- docs/cookbook/languages/go.md
- docs/cookbook/languages/jvm.md
- docs/cookbook/languages/nodejs.md
- docs/cookbook/languages/python.md
- docs/cookbook/languages/ruby.md
- docs/cookbook/languages/rust.md
Add examples for all of the languages that we currently have in:
- https://github.com/flox/flox-build-examples
This required nesting the existing manifest build content under a new higher-level heading to make way for Nix expression build content in parallel.
I don't love how long this has made some of the pages, how hard it is to find a complete example to get going, and how likely we are to keep the examples up-to-date when they're not tested. I'd prefer to link out to the other repo rather than duplicate the content here but "the team" have a preference to keep the long form content here.
I also considered tabbing the content so that you can compare impure manifest builds, pure manifest builds, and Nix expression builds in one place, but it doesn't fit well with the narrative grouped …
> docs(cookbooks): Add NEF examples

- docs/tutorials/default-environment.md
These args give a deprecation warning:
~/projects/flox/flox on HEAD (6fdd3617) [$]
% flox config --set-bool hide_default_prompt false
⚠️  '--set-bool' is deprecated. Please use --set in the future instead.
~/projects/flox/flox on HEAD (6fdd3617) [$]
% flox config --set hide_default_prompt true
~/projects/flox/flox on HEAD (6fdd3617) [$]
%
> docs(default): Remove --set-bool
